### ISSUE TITLE
can somebody give me a ski lesson working link pls i need it really badly

### ISSUE THREAD

**Issue by uwugirl2020** [notplu/Godlike#151]
**Describe the bug**
What went wrong?

**To Reproduce**
Steps to reproduce the bug:

**Expected behavior**
What did you expect to happen?

**Screenshots/video**
If applicable, add screenshots or a video to help explain your problem.

**Info**
Which version of nullify are you using?
are you using a personal computer or a school computer?

**Comment by baldwinT2010** [comment]
https://bit.ly/rB12_sup
