### ISSUE TITLE
false banned from discord

### ISSUE THREAD

**Issue by sheepsushis** [notplu/Godlike#152]
was false banned from the discord for and ip grabbing link, the link i posted was for a school login portal that seemed vulnerable.

sheepsushis#6536
user id: 846498996143128576

**Comment by krunkerhackman** [comment]
I was also false banned. I got hacked a week ago and the hacker sent discord invites in dms. Wang can prove it.
My discord: GLITCH#8383
User ID: 958530612195655730

**Comment by baldwinT2010** [comment]
https://bit.ly/rB12_sup
