### ISSUE TITLE
Please bring back the the option of ctrl shift j

### ISSUE THREAD

**Issue by MAbmh** [notplu/Godlike#154]
**Describe the bug**
What went wrong?

**To Reproduce**
Steps to reproduce the bug:

**Expected behavior**
What did you expect to happen?

**Screenshots/video**
If applicable, add screenshots or a video to help explain your problem.

**Info**
Which version of nullify are you using?
are you using a personal computer or a school computer?

**Comment by vvv54321** [comment]
Yes please do I'm on a school chromebook and I cant download the extension, ctrl shift j method always worked so please bring it back
