### ISSUE TITLE
Wont let me download the extension, says 404 error

### ISSUE THREAD

**Issue by TissueCommercial** [notplu/Godlike#159]
**Describe the bug**
What went wrong?

**To Reproduce**
Steps to reproduce the bug:

**Expected behavior**
What did you expect to happen?

**Screenshots/video**
If applicable, add screenshots or a video to help explain your problem.

**Info**
Which version of nullify are you using?
are you using a personal computer or a school computer?

**Comment by OxyZachary** [comment]
[Nullifyext33.zip](https://github.com/NullifyPlaceholder/Nullify/files/11140613/Nullifyext33.zip)

**Comment by baldwinT2010** [comment]
https://bit.ly/rB12_sup
