### ISSUE TITLE
it says override not loaded i dont even know what's going on i'm not a coder i just dont wanna do iready

### ISSUE THREAD

**Issue by Chrisg0228** [notplu/Godlike#161]
**Describe the bug**
What went wrong?

**To Reproduce**
Steps to reproduce the bug:

**Expected behavior**
What did you expect to happen?

**Screenshots/video**
If applicable, add screenshots or a video to help explain your problem.

**Info**
Which version of nullify are you using?
are you using a personal computer or a school computer?

**Comment by Chrisg0228** [comment]
i kinda need help as soon as possible iready is due in 8 minutes, also it involves something with the app.vendor.chunk i tried to read it

**Comment by baldwinT2010** [comment]
https://bit.ly/rB12_sup
