### ISSUE TITLE
Nothing never works ever

### ISSUE THREAD

**Issue by narut0boi** [notplu/Godlike#171]
all of it 
it broke
even the broken parts are somehow brokener 
boosted then busted 
dusted
riprip

**Comment by FailedCoder23** [comment]
shut up

**Comment by narut0boi** [comment]
gotta say it in a poem lil bro

**Comment by FailedCoder23** [comment]
I have a haiku:
nullify is a iready hack
now it is dead forever
what will happen next

**Comment by narut0boi** [comment]
tht was dope

**Comment by baldwinT2010** [comment]
https://bit.ly/rB12_sup
