### ISSUE TITLE
I ready hack 

### ISSUE THREAD

**Issue by Danny58612** [notplu/Godlike#181]
This is awful what the creator has done by shuting down the system now my life is so much harder my school is underfunded and we get to do 10 iready lessons then it repeats again and again and i need to do them or my grade gets lowerd now my life is so much harder. I feel so upset just think i need to do the same 10 i ready lessons again and again :(. I hope that they can reactivate it for the ones who need or somekind of agreement warning promp when turning the i ready system on

**Comment by uwugirl2020** [comment]
i want it to work to i have to do 2 hours a week

**Comment by FailedCoder23** [comment]
get a life

**Comment by uwugirl2020** [comment]
you to

**Comment by Danny58612** [comment]
FailedCoder23 go fuck off or cuddle with your teddy bear

**Comment by Danny58612** [comment]
you big adult baby
